default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: GovTroll_development

test:
  <<: *default
  database: GovTroll_test

production:
  <<: *default
  database: GovTroll_production
  username: GovTroll
  password: <%= ENV['GOVTROLL_DATABASE_PASSWORD'] %>
